# Generated by Django 5.1.2 on 2024-10-19 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelagency',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='travelagency',
            old_name='verified',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='profile',
        ),
        migrations.AddField(
            model_name='travelagency',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_agencies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagency',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
