# Generated by Django 5.1.2 on 2024-10-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_travelagency_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='tour_package',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tour_package',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='routes',
            field=models.ManyToManyField(blank=True, to='travelapp.route'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='travelapp.vehicle'),
        ),
    ]
