# Generated by Django 5.1.2 on 2024-10-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_remove_route_tour_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelapp.travelagency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelapp.travelagency'),
            preserve_default=False,
        ),
    ]
