# Generated by Django 5.1.2 on 2024-10-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_route_agency_vehicle_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_image/'),
        ),
    ]
