# Generated by Django 5.1.2 on 2024-10-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_tourpackage_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='vehicles',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='travelapp.travelagency'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='availability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
