# Generated by Django 5.1.2 on 2024-10-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_remove_tourpackage_routes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
