# Generated by Django 5.1.2 on 2024-10-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='vehicles',
            field=models.ManyToManyField(related_name='tour_packages', to='travelapp.vehicle'),
        ),
    ]
