# Generated by Django 5.1.2 on 2024-10-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_tourpackage_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='routes',
            field=models.ManyToManyField(related_name='tour_packages', to='travelapp.route'),
        ),
    ]
