# Generated by Django 5.0.4 on 2024-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0012_tourpackage_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='agency_image',
            field=models.ImageField(blank=True, null=True, upload_to='agency/'),
        ),
    ]
