# Generated by Django 5.0.4 on 2024-11-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0013_travelagency_agency_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='from_location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='to_location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
